# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(806, 826)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(806, 826))
        MainWindow.setMaximumSize(QtCore.QSize(806, 826))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.pingButton = QtGui.QPushButton(self.tab)
        self.pingButton.setGeometry(QtCore.QRect(734, 10, 41, 23))
        self.pingButton.setObjectName(_fromUtf8("pingButton"))
        self.pingOut = QtGui.QTextEdit(self.tab)
        self.pingOut.setGeometry(QtCore.QRect(10, 40, 761, 691))
        self.pingOut.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.pingOut.setReadOnly(True)
        self.pingOut.setObjectName(_fromUtf8("pingOut"))
        self.pingIn = QtGui.QLineEdit(self.tab)
        self.pingIn.setGeometry(QtCore.QRect(10, 10, 661, 21))
        self.pingIn.setObjectName(_fromUtf8("pingIn"))
        self.shrinkPing = QtGui.QCheckBox(self.tab)
        self.shrinkPing.setGeometry(QtCore.QRect(680, 10, 51, 17))
        self.shrinkPing.setObjectName(_fromUtf8("shrinkPing"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.whoisButton = QtGui.QPushButton(self.tab_2)
        self.whoisButton.setGeometry(QtCore.QRect(734, 10, 41, 23))
        self.whoisButton.setObjectName(_fromUtf8("whoisButton"))
        self.whoisOut = QtGui.QTextEdit(self.tab_2)
        self.whoisOut.setGeometry(QtCore.QRect(10, 40, 761, 691))
        self.whoisOut.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.whoisOut.setReadOnly(True)
        self.whoisOut.setObjectName(_fromUtf8("whoisOut"))
        self.whoisIn = QtGui.QLineEdit(self.tab_2)
        self.whoisIn.setGeometry(QtCore.QRect(10, 10, 721, 21))
        self.whoisIn.setObjectName(_fromUtf8("whoisIn"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.dnsOut = QtGui.QTextEdit(self.tab_3)
        self.dnsOut.setGeometry(QtCore.QRect(10, 40, 761, 691))
        self.dnsOut.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.dnsOut.setReadOnly(True)
        self.dnsOut.setObjectName(_fromUtf8("dnsOut"))
        self.dnsButton = QtGui.QPushButton(self.tab_3)
        self.dnsButton.setGeometry(QtCore.QRect(734, 10, 41, 23))
        self.dnsButton.setObjectName(_fromUtf8("dnsButton"))
        self.dnsIn = QtGui.QLineEdit(self.tab_3)
        self.dnsIn.setGeometry(QtCore.QRect(10, 10, 521, 21))
        self.dnsIn.setObjectName(_fromUtf8("dnsIn"))
        self.dnsRec = QtGui.QComboBox(self.tab_3)
        self.dnsRec.setGeometry(QtCore.QRect(660, 10, 69, 22))
        self.dnsRec.setEditable(False)
        self.dnsRec.setMaxVisibleItems(16)
        self.dnsRec.setObjectName(_fromUtf8("dnsRec"))
        self.dnsSrv = QtGui.QLineEdit(self.tab_3)
        self.dnsSrv.setGeometry(QtCore.QRect(540, 10, 111, 21))
        self.dnsSrv.setObjectName(_fromUtf8("dnsSrv"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.portIn = QtGui.QLineEdit(self.tab_4)
        self.portIn.setGeometry(QtCore.QRect(10, 10, 641, 21))
        self.portIn.setObjectName(_fromUtf8("portIn"))
        self.portButton = QtGui.QPushButton(self.tab_4)
        self.portButton.setGeometry(QtCore.QRect(734, 10, 41, 23))
        self.portButton.setObjectName(_fromUtf8("portButton"))
        self.portOut = QtGui.QTextEdit(self.tab_4)
        self.portOut.setGeometry(QtCore.QRect(10, 40, 761, 691))
        self.portOut.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.portOut.setReadOnly(True)
        self.portOut.setObjectName(_fromUtf8("portOut"))
        self.portBox = QtGui.QLineEdit(self.tab_4)
        self.portBox.setGeometry(QtCore.QRect(660, 10, 71, 20))
        self.portBox.setObjectName(_fromUtf8("portBox"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.traceButton = QtGui.QPushButton(self.tab_11)
        self.traceButton.setGeometry(QtCore.QRect(734, 10, 41, 23))
        self.traceButton.setObjectName(_fromUtf8("traceButton"))
        self.traceOut = QtGui.QTextEdit(self.tab_11)
        self.traceOut.setGeometry(QtCore.QRect(10, 40, 761, 691))
        self.traceOut.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.traceOut.setReadOnly(True)
        self.traceOut.setObjectName(_fromUtf8("traceOut"))
        self.traceIn = QtGui.QLineEdit(self.tab_11)
        self.traceIn.setGeometry(QtCore.QRect(10, 10, 651, 21))
        self.traceIn.setObjectName(_fromUtf8("traceIn"))
        self.resolveTrace = QtGui.QCheckBox(self.tab_11)
        self.resolveTrace.setGeometry(QtCore.QRect(670, 10, 61, 17))
        self.resolveTrace.setObjectName(_fromUtf8("resolveTrace"))
        self.tabWidget.addTab(self.tab_11, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.allOut = QtGui.QTextEdit(self.tab_5)
        self.allOut.setGeometry(QtCore.QRect(10, 40, 761, 691))
        self.allOut.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.allOut.setReadOnly(True)
        self.allOut.setObjectName(_fromUtf8("allOut"))
        self.allButton = QtGui.QPushButton(self.tab_5)
        self.allButton.setGeometry(QtCore.QRect(734, 10, 41, 23))
        self.allButton.setObjectName(_fromUtf8("allButton"))
        self.allIn = QtGui.QLineEdit(self.tab_5)
        self.allIn.setGeometry(QtCore.QRect(10, 10, 721, 21))
        self.allIn.setObjectName(_fromUtf8("allIn"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Options = QtGui.QMenu(self.menubar)
        self.menu_Options.setObjectName(_fromUtf8("menu_Options"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Exit = QtGui.QAction(MainWindow)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.action_Prefrences = QtGui.QAction(MainWindow)
        self.action_Prefrences.setObjectName(_fromUtf8("action_Prefrences"))
        self.menu_File.addAction(self.action_Exit)
        self.menu_Options.addAction(self.action_Prefrences)
        self.menu_Help.addAction(self.action_About)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Options.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Get info", None))
        self.pingButton.setText(_translate("MainWindow", "Ping", None))
        self.pingOut.setPlainText(_translate("MainWindow", "Ping output will be displayed here...", None))
        self.pingIn.setPlaceholderText(_translate("MainWindow", "Enter address to ping...", None))
        self.shrinkPing.setText(_translate("MainWindow", "Shrink", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "&1 - Ping", None))
        self.whoisButton.setText(_translate("MainWindow", "Whois", None))
        self.whoisOut.setPlainText(_translate("MainWindow", "Whois output will be displayed here...", None))
        self.whoisIn.setPlaceholderText(_translate("MainWindow", "Enter address to whois...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "&2 - Who is", None))
        self.dnsOut.setPlainText(_translate("MainWindow", "DNS records output will be displayed here...", None))
        self.dnsButton.setText(_translate("MainWindow", "DNS", None))
        self.dnsIn.setPlaceholderText(_translate("MainWindow", "Enter address to read DNS records...", None))
        self.dnsSrv.setPlaceholderText(_translate("MainWindow", "Enter server...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "&3 - DNS query", None))
        self.portIn.setPlaceholderText(_translate("MainWindow", "Enter address...", None))
        self.portButton.setText(_translate("MainWindow", "Check", None))
        self.portOut.setPlainText(_translate("MainWindow", "Output will be here...", None))
        self.portBox.setInputMask(_translate("MainWindow", "00000", None))
        self.portBox.setPlaceholderText(_translate("MainWindow", "Port...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "&4 - Port check", None))
        self.traceButton.setText(_translate("MainWindow", "Trace", None))
        self.traceOut.setPlainText(_translate("MainWindow", "Trace will be displayed here...", None))
        self.traceIn.setPlaceholderText(_translate("MainWindow", "Enter address to trace...", None))
        self.resolveTrace.setText(_translate("MainWindow", "Resolve", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "&5 - Trace", None))
        self.allOut.setPlainText(_translate("MainWindow", "Address info will be displayed here...", None))
        self.allButton.setText(_translate("MainWindow", "Info", None))
        self.allIn.setPlaceholderText(_translate("MainWindow", "Enter address to get all info...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "&6 - All", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Options.setTitle(_translate("MainWindow", "&Options", None))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help", None))
        self.action_Exit.setText(_translate("MainWindow", "&Exit", None))
        self.action_Exit.setShortcut(_translate("MainWindow", "Alt+X", None))
        self.action_About.setText(_translate("MainWindow", "&About", None))
        self.action_Prefrences.setText(_translate("MainWindow", "&Prefrences", None))
        self.action_Prefrences.setShortcut(_translate("MainWindow", "Ctrl+P", None))

